#TradierCred
ACCOUNTID = "6YA30644"
ACCESSTOKEN = "iXmgRD99BBYAhXwHBFhsDacOlmkE"
PAPER_ACCOUNTID = "VA72174659"
PAPER_ACCESSTOKEN = "ld0Mx4KbsOBYwmJApdowZdFcIxO7"
PAPER_BASE_URL = "https://sandbox.tradier.com/v1/"
LIVE_BASE_URL = "https://api.tradier.com/v1/"
# PAPER_ACCOUNTID = "VA80685931"
# PAPER_ACCESSTOKEN = "txhklwGnxNbFGNtryB1c4O8RAg5P"