service: icarus-trading-engine

frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions

functions:
  icarus-trade-builder:
    handler: icarus_trade_builder.run
    environment:
      PREDICTIONS_BUCKET: "yqalerts-raw-predictions"
      ALERTS_BUCKET: "yqalerts-processed-alerts"
      TITLE: "gainers"
      ENDPOINT_NAME: "xgboost-gainers-classifier"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-sls
  new-trades-portfolio-manager:
    handler: new_trades_portfolio_manager.run_pipeline
    environment:
      PREDICTIONS_BUCKET: "yqalerts-raw-predictions"
      ALERTS_BUCKET: "yqalerts-processed-alerts"
      TITLE: "gainers"
      SCREENER_TITLE: "day_gainers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: new-trades-portfolio-manager-sls
  open-trades-portfolio-manager:
    handler: open_trades_portfolio_manager.run_pipeline
    environment:
      PREDICTIONS_BUCKET: "yqalerts-raw-predictions"
      ALERTS_BUCKET: "yqalerts-processed-alerts"
      TITLE: "gainers"
      SCREENER_TITLE: "day_gainers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: open-trades-portfolio-manager-sls
  trade-executor:
    handler: trade_executor.aggregate
    environment:
      PREDICTIONS_BUCKET: "yqalerts-raw-predictions"
      FINAL_BUCKET: "yqalerts-model-results"
      ALERTS_BUCKET: "yqalerts-processed-alerts"
      TITLE: "gainers"
      SCREENER_TITLE: "day_gainers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: trade-executor-sls
        
  
 
stepFunctions:
  stateMachines:
    icarus-new-trades:
      name: icarus-new-trades
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: !Ref yqalertsTopic
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: BuildTrade
        States:
          BuildTrade:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-sls
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: ExpandedFeatureBuilder
          PortfolioManager:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:new-trades-portfolio-manager-sls
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          TradeExecutor:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:trade-executor-sls
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
            Type: Succeed
    icarus-open-trades:
      name: icarus-open-trades
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: !Ref yqalertsTopic
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: PortfolioManager
        States:
          PortfolioManager:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:open-trades-portfolio-manager-sls
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          TradeExecutor:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:trade-executor
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
            Type: Succeed

resources:
  Resources:
    yqalertsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: yqalerts-production-modeling
