service: icarus-trading-engine
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

functions:
  icarus-trade-builder:
    handler: icarus_trade_builder.run
    environment:
      MODEL_RESULTS_BUCKET: "yqalerts-model-results"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder
  new-trades-portfolio-manager-paper:
    handler: new_trades_portfolio_manager.manage_portfolio
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: new-trades-portfolio-manager-paper
  open-trades-portfolio-manage-paper:
    handler: open_trades_portfolio_manager.manage_portfolio
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: open-trades-portfolio-manager-paper
        
  
 
stepFunctions:
  stateMachines:
    icarus-new-trades:
      name: icarus-new-trades
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: BuildTrade
        States:
          BuildTrade:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: PortfolioManager
          PortfolioManager:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:new-trades-portfolio-manager-paper
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
            Type: Succeed
    # icarus-open-trades:
    #   name: icarus-open-trades
    #   role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
    #   alarms:
    #     topics:
    #       alarm: !Ref yqalertsTopic
    #     metrics:
    #       - executionsTimedOut
    #       - executionsFailed
    #       - executionsAborted
    #       - executionThrottled
    #     treatMissingData: missing
    #   definition:
    #     Comment: "This state machine constructs and executes trades based on results of the modeling engine"
    #     StartAt: PortfolioManager
    #     States:
    #       PortfolioManager:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:456201388658:function:open-trades-portfolio-manager-sls
    #         Retry:
    #         - ErrorEquals:
    #           - Lambda.ServiceException
    #           - Lambda.AWSLambdaException
    #           - Lambda.SdkClientException
    #           IntervalSeconds: 5
    #           MaxAttempts: 3
    #           BackoffRate: 2
    #         Next: End
    #       TradeExecutor:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:456201388658:function:trade-executor
    #         Retry:
    #         - ErrorEquals:
    #           - Lambda.ServiceException
    #           - Lambda.AWSLambdaException
    #           - Lambda.SdkClientException
    #           IntervalSeconds: 5
    #           MaxAttempts: 3
    #           BackoffRate: 2
    #         Next: End
    #       End:
    #         Type: Succeed
