service: icarus-trading-engine
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

functions:
  icarus-trade-builder:
    handler: icarus_trade_builder.build_trade
    environment:
      MODEL_RESULTS_BUCKET: "yqalerts-model-results"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "yq"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder
  new-trades-portfolio-manager-paper:
    handler: new_trades_portfolio_manager.manage_portfolio
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "yq"
      TABLE: "icarus-orders-table"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: new-trades-portfolio-manager-paper
  open-trades-portfolio-manage-paper:
    handler: open_trades_portfolio_manager.manage_portfolio
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      TABLE: "icarus-orders-table"
      CLOSE_TABLE: "icarus-closed-orders-table"
      USER: "yq"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: open-trades-portfolio-manager-paper
  icarus-trade-builder-invDG:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "day_gainers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invDG
  icarus-trade-builder-invDL:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "day_losers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invDL
  icarus-trade-builder-invMA:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "most_actives"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invMA
  icarus-trade-builder-invMAP:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "maP"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invMAP
  icarus-trade-builder-invVDGC:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "vdiff_gainC"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invVDGC
  icarus-trade-builder-invVDGP:
    handler: icarus_trade_builder.build_trade_inv
    environment:
      MODEL_RESULTS_BUCKET: "inv-alerts-trading-data"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "inv"
      TRADING_STRATEGY: "vdiff_gainP"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: icarus-trade-builder-paper-invVDGP
  new-trades-portfolio-manager-paper-inv:
    handler: new_trades_portfolio_manager.manage_portfolio_inv
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "inv-alerts-trading-data"
      USER: "inv"
      TABLE: "icarus-orders-table-inv"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: new-trades-portfolio-manager-paper-inv
  open-trades-portfolio-manage-paper-inv:
    handler: open_trades_portfolio_manager.manage_portfolio
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "inv-alerts-trading-data"
      USER: "inv"
      TABLE: "icarus-orders-table-inv"
      CLOSE_TABLE: "icarus-closed-orders-table-inv"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: open-trades-portfolio-manager-paper-inv
  open-trades-reconciliation:
    handler: order_reconciliation.run_reconciliation
    environment:
      TRADING_MODE: "PAPER"
      TRADING_DATA_BUCKET: "icarus-trading-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: open-trades-reconciliation
  order-controls:
      handler: order_control.run_order_control
      environment:
        TRADING_MODE: "PAPER"
        TRADING_DATA_BUCKET: "icarus-trading-data"
        USER: "CM3"
      layers:
        - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
      name: order-controls
        
  
 
stepFunctions:
  stateMachines:
    icarus-new-trades:
      name: icarus-new-trades
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: ParallelProcessor
        States:
          ParallelProcessor:
            Type: Parallel
            Branches:
              - StartAt: BuildTrade
                States:
                  BuildTrade:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: open-trades-portfolio-manage-paper
                States:
                  open-trades-portfolio-manage-paper:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:open-trades-portfolio-manager-paper:$LATEST"
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
            Next: PortfolioManager
          PortfolioManager:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:new-trades-portfolio-manager-paper
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
            Type: Succeed
    icarus-new-trades-inv:
      name: icarus-new-trades-inv
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: ParallelProcessorINV
        States:
          ParallelProcessorINV:
            Type: Parallel
            Branches:
              - StartAt: BuildTradeDG
                States:
                  BuildTradeDG:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invDG
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: BuildTradeDL
                States:
                  BuildTradeDL:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invDL
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: BuildTradeMA
                States:
                  BuildTradeMA:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invMA
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: BuildTradeMAP
                States:
                  BuildTradeMAP:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invMAP
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: BuildTradeVDGC
                States:
                  BuildTradeVDGC:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invVDGC
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: BuildTradeVDGP
                States:
                  BuildTradeVDGP:
                    Type: Task
                    Resource: arn:aws:lambda:us-east-1:456201388658:function:icarus-trade-builder-paper-invVDGP
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    End: True
              - StartAt: open-trades-portfolio-manage-paperINV
                States:
                  open-trades-portfolio-manage-paperINV:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:open-trades-portfolio-manager-paper-inv:$LATEST"
                    Retry:
                    - ErrorEquals:
                      - Lambda.ServiceException
                      - Lambda.AWSLambdaException
                      - Lambda.SdkClientException
                      IntervalSeconds: 5
                      MaxAttempts: 3
                      BackoffRate: 2
                    # ResultPath: $.open_positions
                    End: True
            Next: PortfolioManagerINV
          PortfolioManagerINV:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:new-trades-portfolio-manager-paper-inv
            Parameters:
              Payload.$: $
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
            Type: Succeed
    # icarus-open-trades:
    #   name: icarus-open-trades
    #   role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
    #   alarms:
    #     topics:
    #       alarm: !Ref yqalertsTopic
    #     metrics:
    #       - executionsTimedOut
    #       - executionsFailed
    #       - executionsAborted
    #       - executionThrottled
    #     treatMissingData: missing
    #   definition:
    #     Comment: "This state machine constructs and executes trades based on results of the modeling engine"
    #     StartAt: PortfolioManager
    #     States:
    #       PortfolioManager:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:456201388658:function:open-trades-portfolio-manager-sls
    #         Retry:
    #         - ErrorEquals:
    #           - Lambda.ServiceException
    #           - Lambda.AWSLambdaException
    #           - Lambda.SdkClientException
    #           IntervalSeconds: 5
    #           MaxAttempts: 3
    #           BackoffRate: 2
    #         Next: End
    #       TradeExecutor:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:456201388658:function:trade-executor
    #         Retry:
    #         - ErrorEquals:
    #           - Lambda.ServiceException
    #           - Lambda.AWSLambdaException
    #           - Lambda.SdkClientException
    #           IntervalSeconds: 5
    #           MaxAttempts: 3
    #           BackoffRate: 2
    #         Next: End
    #       End:
    #         Type: Succeed